[package]
name = "petal_tests"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rstest = "0.18.2"
petal_runtime = { path = "../petal_runtime" }
petal_core = { path = "../petal_core" }
