on: [push]

name: CI

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '(cargo-release)')"
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install tools via mise
        uses: jdx/mise-action@v2

      - name: Cache cargo
        uses: Swatinem/rust-cache@v2

      - name: Run cargo check
        run: cargo check

  lints:
    name: Lints
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '(cargo-release)')"
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install tools via mise
        uses: jdx/mise-action@v2

      - name: Cache cargo
        uses: Swatinem/rust-cache@v2

      - name: Run cargo fmt
        run: cargo fmt --all -- --check

      - name: Run cargo clippy
        run: cargo clippy --all-targets --all-features

  test:
    name: Test Suite
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    if: "!contains(github.event.head_commit.message, '(cargo-release)')"
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install tools via mise
        uses: jdx/mise-action@v2

      - name: Cache cargo
        uses: Swatinem/rust-cache@v2

      - name: Run cargo test
        run: cargo test --all
